CREATE TABLE IF NOT EXISTS operation_events (
  operation_event_id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  station_id TEXT,
  shipment_id TEXT,
  flight_id TEXT,
  awb_id TEXT,
  aggregate_type TEXT NOT NULL,
  aggregate_id TEXT NOT NULL,
  aggregate_sequence INTEGER NOT NULL,
  event_type TEXT NOT NULL,
  event_action TEXT,
  occurred_at TEXT NOT NULL,
  recorded_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actor_id TEXT NOT NULL,
  actor_role TEXT NOT NULL,
  client_source TEXT NOT NULL,
  client_event_id TEXT,
  idempotency_key TEXT NOT NULL,
  correlation_id TEXT,
  causation_id TEXT,
  reason_code TEXT,
  payload_json TEXT NOT NULL DEFAULT '{}',
  correction_of_event_id TEXT,
  FOREIGN KEY (station_id) REFERENCES stations(station_id),
  FOREIGN KEY (shipment_id) REFERENCES shipments(shipment_id),
  FOREIGN KEY (flight_id) REFERENCES flights(flight_id),
  FOREIGN KEY (awb_id) REFERENCES awbs(awb_id),
  FOREIGN KEY (correction_of_event_id) REFERENCES operation_events(operation_event_id),
  UNIQUE(tenant_id, idempotency_key),
  UNIQUE(tenant_id, aggregate_type, aggregate_id, aggregate_sequence)
);

CREATE INDEX IF NOT EXISTS idx_operation_events_shipment_time
  ON operation_events(shipment_id, occurred_at);
CREATE INDEX IF NOT EXISTS idx_operation_events_aggregate
  ON operation_events(aggregate_type, aggregate_id, aggregate_sequence);

CREATE TABLE IF NOT EXISTS evidences (
  evidence_id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  station_id TEXT,
  shipment_id TEXT,
  related_object_type TEXT NOT NULL,
  related_object_id TEXT NOT NULL,
  evidence_type TEXT NOT NULL,
  file_name TEXT,
  content_type TEXT,
  storage_key TEXT,
  source_type TEXT NOT NULL DEFAULT 'USER_UPLOAD',
  source_ref TEXT,
  sha256 TEXT,
  occurred_at TEXT,
  captured_at TEXT,
  uploaded_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  uploaded_by TEXT NOT NULL,
  metadata_json TEXT NOT NULL DEFAULT '{}',
  retention_until TEXT,
  archived_at TEXT,
  FOREIGN KEY (station_id) REFERENCES stations(station_id),
  FOREIGN KEY (shipment_id) REFERENCES shipments(shipment_id)
);

CREATE INDEX IF NOT EXISTS idx_evidences_related_object
  ON evidences(related_object_type, related_object_id, uploaded_at DESC);

CREATE TABLE IF NOT EXISTS gate_decisions (
  gate_decision_id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  gate_code TEXT NOT NULL,
  related_object_type TEXT NOT NULL,
  related_object_id TEXT NOT NULL,
  decision TEXT NOT NULL,
  action_complete INTEGER NOT NULL DEFAULT 0,
  data_consistent INTEGER NOT NULL DEFAULT 0,
  evidence_complete INTEGER NOT NULL DEFAULT 0,
  next_owner_accepted INTEGER NOT NULL DEFAULT 0,
  conditions_json TEXT NOT NULL DEFAULT '{}',
  applicable_cargo_unit_ids_json TEXT NOT NULL DEFAULT '[]',
  reason TEXT,
  requested_by TEXT NOT NULL,
  decided_by TEXT NOT NULL,
  decided_at TEXT NOT NULL,
  expires_at TEXT,
  version_no INTEGER NOT NULL DEFAULT 1,
  supersedes_gate_decision_id TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (decision IN ('PASS', 'CONDITIONAL_PASS', 'BLOCKED', 'REVOKED')),
  CHECK (requested_by <> decided_by),
  FOREIGN KEY (supersedes_gate_decision_id) REFERENCES gate_decisions(gate_decision_id)
);

CREATE INDEX IF NOT EXISTS idx_gate_decisions_object
  ON gate_decisions(related_object_type, related_object_id, gate_code, version_no DESC);

CREATE TABLE IF NOT EXISTS cargo_baseline_versions (
  baseline_version_id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  shipment_id TEXT NOT NULL,
  version_no INTEGER NOT NULL,
  baseline_type TEXT NOT NULL DEFAULT 'EXPECTED',
  status TEXT NOT NULL DEFAULT 'DRAFT',
  expected_pieces INTEGER NOT NULL,
  expected_weight_kg REAL,
  source_type TEXT NOT NULL,
  source_ref TEXT,
  change_reason TEXT,
  requested_by TEXT NOT NULL,
  approved_by TEXT,
  published_at TEXT,
  supersedes_version_id TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (status IN ('DRAFT', 'IN_REVIEW', 'PUBLISHED', 'SUPERSEDED')),
  FOREIGN KEY (shipment_id) REFERENCES shipments(shipment_id),
  FOREIGN KEY (supersedes_version_id) REFERENCES cargo_baseline_versions(baseline_version_id),
  UNIQUE(tenant_id, shipment_id, baseline_type, version_no)
);

CREATE TABLE IF NOT EXISTS cargo_units (
  cargo_unit_id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  shipment_id TEXT NOT NULL,
  awb_id TEXT,
  hawb_no TEXT,
  business_barcode TEXT NOT NULL,
  barcode_type TEXT NOT NULL DEFAULT 'PACKAGE',
  unit_sequence INTEGER,
  parent_unit_id TEXT,
  package_type TEXT,
  expected_weight_kg REAL,
  actual_weight_kg REAL,
  condition_status TEXT NOT NULL DEFAULT 'NORMAL',
  inventory_state TEXT NOT NULL DEFAULT 'EXPECTED',
  current_location_type TEXT,
  current_location_id TEXT,
  expected_baseline_version_id TEXT NOT NULL,
  aggregate_quantity INTEGER NOT NULL DEFAULT 1,
  is_aggregate INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  archived_at TEXT,
  CHECK (condition_status IN ('NORMAL', 'DAMAGED', 'WET', 'OPENED', 'DEFORMED', 'LABEL_ISSUE', 'OTHER')),
  CHECK (inventory_state IN ('EXPECTED', 'PREWH_RECEIVED', 'LOADED', 'IN_TRANSIT', 'TAS_RECEIVED', 'QUARANTINED', 'RELEASED')),
  FOREIGN KEY (shipment_id) REFERENCES shipments(shipment_id),
  FOREIGN KEY (awb_id) REFERENCES awbs(awb_id),
  FOREIGN KEY (parent_unit_id) REFERENCES cargo_units(cargo_unit_id),
  FOREIGN KEY (expected_baseline_version_id) REFERENCES cargo_baseline_versions(baseline_version_id),
  UNIQUE(tenant_id, business_barcode)
);

CREATE INDEX IF NOT EXISTS idx_cargo_units_shipment_state
  ON cargo_units(shipment_id, inventory_state);

CREATE TABLE IF NOT EXISTS warehouse_receipt_sessions (
  receipt_session_id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  shipment_id TEXT NOT NULL,
  warehouse_station_id TEXT NOT NULL,
  batch_no TEXT NOT NULL,
  source_delivery_ref TEXT,
  source_vehicle_plate TEXT,
  expected_baseline_version_id TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'EXPECTED',
  started_at TEXT,
  submitted_at TEXT,
  approved_at TEXT,
  expected_pieces INTEGER NOT NULL,
  unique_received_pieces INTEGER NOT NULL DEFAULT 0,
  normal_pieces INTEGER NOT NULL DEFAULT 0,
  exception_pieces INTEGER NOT NULL DEFAULT 0,
  operator_id TEXT,
  supervisor_id TEXT,
  gate_decision_id TEXT,
  version_no INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (status IN ('EXPECTED', 'IN_PROGRESS', 'SUBMITTED', 'APPROVED', 'BLOCKED', 'CANCELLED')),
  FOREIGN KEY (shipment_id) REFERENCES shipments(shipment_id),
  FOREIGN KEY (warehouse_station_id) REFERENCES stations(station_id),
  FOREIGN KEY (expected_baseline_version_id) REFERENCES cargo_baseline_versions(baseline_version_id),
  FOREIGN KEY (gate_decision_id) REFERENCES gate_decisions(gate_decision_id)
);

CREATE TABLE IF NOT EXISTS count_events (
  count_event_id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  session_type TEXT NOT NULL,
  session_id TEXT NOT NULL,
  shipment_id TEXT NOT NULL,
  cargo_unit_id TEXT,
  event_action TEXT NOT NULL,
  quantity_delta INTEGER NOT NULL,
  location_type TEXT NOT NULL,
  location_id TEXT NOT NULL,
  condition_status TEXT,
  weight_kg REAL,
  occurred_at TEXT NOT NULL,
  recorded_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actor_id TEXT NOT NULL,
  device_id TEXT,
  client_event_id TEXT NOT NULL,
  idempotency_key TEXT NOT NULL,
  offline_created INTEGER NOT NULL DEFAULT 0,
  sync_status TEXT NOT NULL DEFAULT 'SYNCED',
  reason_code TEXT,
  evidence_refs_json TEXT NOT NULL DEFAULT '[]',
  reverses_count_event_id TEXT,
  CHECK (session_type IN ('PREWAREHOUSE', 'AIRPORT_TAS')),
  CHECK (event_action IN ('SCAN_IN', 'BULK_COUNT', 'MARK_EXCEPTION', 'REVERSE', 'CORRECT')),
  CHECK (sync_status IN ('PENDING', 'SYNCED', 'CONFLICT', 'FAILED')),
  FOREIGN KEY (shipment_id) REFERENCES shipments(shipment_id),
  FOREIGN KEY (cargo_unit_id) REFERENCES cargo_units(cargo_unit_id),
  FOREIGN KEY (reverses_count_event_id) REFERENCES count_events(count_event_id),
  UNIQUE(tenant_id, client_event_id),
  UNIQUE(tenant_id, idempotency_key)
);

CREATE INDEX IF NOT EXISTS idx_count_events_session
  ON count_events(session_type, session_id, recorded_at);
CREATE INDEX IF NOT EXISTS idx_count_events_cargo_unit
  ON count_events(cargo_unit_id, occurred_at);

CREATE TABLE IF NOT EXISTS route_templates (
  route_template_id TEXT PRIMARY KEY,
  route_template_code TEXT NOT NULL,
  version_no INTEGER NOT NULL,
  status TEXT NOT NULL DEFAULT 'DRAFT',
  origin_code TEXT NOT NULL,
  destination_code TEXT NOT NULL,
  origin_airport_code TEXT,
  cn_exit_port_code TEXT,
  kz_entry_port_code TEXT,
  port_pair_code TEXT,
  alternate_port_allowed INTEGER NOT NULL DEFAULT 0,
  domestic_corridor_codes_json TEXT NOT NULL DEFAULT '[]',
  kz_corridor_codes_json TEXT NOT NULL DEFAULT '[]',
  schedule_source_status TEXT NOT NULL,
  schedule_approval_status TEXT NOT NULL,
  distance_validation_status TEXT NOT NULL DEFAULT 'TO_BE_CONFIRMED',
  geofence_validation_status TEXT NOT NULL DEFAULT 'TO_BE_CONFIRMED',
  operation_mode_validation_status TEXT NOT NULL DEFAULT 'TO_BE_CONFIRMED',
  effective_from TEXT,
  effective_to TEXT,
  supersedes_route_template_id TEXT,
  source_document_refs_json TEXT NOT NULL DEFAULT '[]',
  approval_ref TEXT,
  created_by TEXT NOT NULL,
  reviewed_by TEXT,
  published_by TEXT,
  published_at TEXT,
  retired_at TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (status IN ('DRAFT', 'IN_REVIEW', 'PUBLISHED', 'RETIRED')),
  CHECK (schedule_approval_status IN ('PENDING_APPROVAL', 'APPROVED_FOR_PILOT', 'APPROVED_FOR_PRODUCTION', 'RETIRED')),
  UNIQUE(route_template_code, version_no),
  FOREIGN KEY (supersedes_route_template_id) REFERENCES route_templates(route_template_id)
);

CREATE TABLE IF NOT EXISTS checkpoint_templates (
  checkpoint_template_id TEXT PRIMARY KEY,
  route_template_id TEXT NOT NULL,
  route_template_version INTEGER NOT NULL,
  checkpoint_code TEXT NOT NULL,
  name_zh TEXT NOT NULL,
  name_en TEXT NOT NULL,
  sequence INTEGER NOT NULL,
  checkpoint_type TEXT NOT NULL,
  location_json TEXT,
  timezone TEXT NOT NULL,
  planned_offset_minutes INTEGER,
  warning_before_minutes INTEGER,
  late_after_minutes INTEGER,
  stale_location_minutes INTEGER,
  confirmation_policy TEXT NOT NULL,
  required_fields_json TEXT NOT NULL DEFAULT '[]',
  required_evidence_types_json TEXT NOT NULL DEFAULT '[]',
  blocking_policy TEXT NOT NULL DEFAULT 'NONE',
  escalation_rule_json TEXT NOT NULL DEFAULT '{}',
  active_from TEXT,
  active_to TEXT,
  FOREIGN KEY (route_template_id) REFERENCES route_templates(route_template_id),
  UNIQUE(route_template_id, route_template_version, checkpoint_code),
  UNIQUE(route_template_id, route_template_version, sequence)
);

CREATE TABLE IF NOT EXISTS transport_jobs (
  transport_job_id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  station_id TEXT NOT NULL,
  shipment_id TEXT NOT NULL,
  flight_id TEXT,
  awb_ids_json TEXT NOT NULL DEFAULT '[]',
  origin_facility_id TEXT NOT NULL,
  destination_facility_id TEXT NOT NULL,
  route_template_id TEXT NOT NULL,
  route_template_version INTEGER NOT NULL,
  planned_loading_at TEXT,
  planned_departure_at TEXT,
  planned_arrival_at TEXT,
  actual_departure_at TEXT,
  actual_arrival_at TEXT,
  actual_departure_receipt_ref TEXT,
  first_valid_gps_event_id TEXT,
  a1_a2_handover_id TEXT,
  status TEXT NOT NULL DEFAULT 'DRAFT',
  health_state TEXT NOT NULL DEFAULT 'UNKNOWN',
  current_control_segment TEXT,
  current_control_owner_assignment_id TEXT,
  next_control_owner_assignment_id TEXT,
  carrier_party_id TEXT,
  dispatcher_id TEXT,
  vehicle_driver_snapshot_id TEXT,
  loaded_pieces INTEGER NOT NULL DEFAULT 0,
  loaded_weight_kg REAL NOT NULL DEFAULT 0,
  seal_number TEXT,
  planned_capacity_weight_kg REAL,
  planned_capacity_volume_m3 REAL,
  verified_legal_load_kg REAL,
  verified_axle_limit_ref TEXT,
  current_checkpoint_instance_id TEXT,
  next_checkpoint_instance_id TEXT,
  last_location_event_id TEXT,
  last_location_at TEXT,
  eta_at TEXT,
  eta_source TEXT,
  eta_confidence REAL,
  tas_staging_arrived_at TEXT,
  tas_receiving_started_at TEXT,
  airport_receipt_session_id TEXT,
  row_version INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (status IN ('DRAFT', 'PLANNED', 'READY_FOR_LOADING', 'LOADING', 'LOADED', 'IN_TRANSIT', 'DELAY_RISK', 'DELAYED', 'ARRIVED_TAS_STAGING', 'TAS_RECEIVING_STARTED', 'HANDOVER_IN_PROGRESS', 'DELIVERED_TO_AIRPORT', 'COMPLETED', 'CANCELLED')),
  CHECK (health_state IN ('UNKNOWN', 'BLUE', 'YELLOW', 'RED', 'STALE')),
  FOREIGN KEY (station_id) REFERENCES stations(station_id),
  FOREIGN KEY (shipment_id) REFERENCES shipments(shipment_id),
  FOREIGN KEY (flight_id) REFERENCES flights(flight_id),
  FOREIGN KEY (route_template_id) REFERENCES route_templates(route_template_id)
);

CREATE INDEX IF NOT EXISTS idx_transport_jobs_shipment
  ON transport_jobs(shipment_id, status);
CREATE INDEX IF NOT EXISTS idx_transport_jobs_flight
  ON transport_jobs(flight_id, status);

CREATE TABLE IF NOT EXISTS vehicle_driver_snapshots (
  vehicle_driver_snapshot_id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  transport_job_id TEXT NOT NULL,
  snapshot_version INTEGER NOT NULL,
  snapshot_scope TEXT NOT NULL DEFAULT 'PRIMARY',
  carrier_party_id TEXT,
  vehicle_plate TEXT NOT NULL,
  vehicle_type TEXT NOT NULL,
  tractor_plate TEXT,
  trailer_plate TEXT,
  legal_load_kg REAL,
  gross_weight_limit_kg REAL,
  axle_limit_ref TEXT,
  insurance_valid_until TEXT,
  driver_name TEXT NOT NULL,
  driver_phone_encrypted TEXT,
  driver_document_ref TEXT,
  backup_driver_name TEXT,
  gps_provider_code TEXT,
  external_vehicle_id TEXT,
  gps_device_no TEXT,
  seal_number TEXT,
  pieces INTEGER NOT NULL DEFAULT 0,
  weight_kg REAL NOT NULL DEFAULT 0,
  active_flag INTEGER NOT NULL DEFAULT 1,
  change_reason TEXT,
  created_by TEXT NOT NULL,
  approved_by TEXT,
  effective_at TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (transport_job_id) REFERENCES transport_jobs(transport_job_id),
  UNIQUE(transport_job_id, snapshot_version)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_vehicle_driver_snapshot_active
  ON vehicle_driver_snapshots(transport_job_id, snapshot_scope)
  WHERE active_flag = 1;

CREATE TABLE IF NOT EXISTS cargo_unit_transport_assignments (
  assignment_id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  cargo_unit_id TEXT NOT NULL,
  transport_job_id TEXT NOT NULL,
  assignment_status TEXT NOT NULL DEFAULT 'ACTIVE',
  loaded_at TEXT,
  unloaded_at TEXT,
  assigned_by TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (assignment_status IN ('ACTIVE', 'UNLOADED', 'CANCELLED')),
  FOREIGN KEY (cargo_unit_id) REFERENCES cargo_units(cargo_unit_id),
  FOREIGN KEY (transport_job_id) REFERENCES transport_jobs(transport_job_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_cargo_unit_active_transport
  ON cargo_unit_transport_assignments(cargo_unit_id)
  WHERE assignment_status = 'ACTIVE';

CREATE TABLE IF NOT EXISTS checkpoint_instances (
  checkpoint_instance_id TEXT PRIMARY KEY,
  transport_job_id TEXT NOT NULL,
  checkpoint_template_id TEXT NOT NULL,
  template_version INTEGER NOT NULL,
  sequence INTEGER NOT NULL,
  planned_arrival_at TEXT,
  planned_departure_at TEXT,
  actual_arrival_at TEXT,
  actual_departure_at TEXT,
  status TEXT NOT NULL DEFAULT 'PENDING',
  confirmation_source TEXT,
  confirmed_by TEXT,
  arrival_location_event_id TEXT,
  departure_location_event_id TEXT,
  evidence_refs_json TEXT NOT NULL DEFAULT '[]',
  exception_ids_json TEXT NOT NULL DEFAULT '[]',
  row_version INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (status IN ('PENDING', 'APPROACHING', 'ARRIVED_CANDIDATE', 'ARRIVED', 'DEPARTED', 'MISSED', 'WAIVED', 'NEEDS_REVIEW')),
  FOREIGN KEY (transport_job_id) REFERENCES transport_jobs(transport_job_id),
  FOREIGN KEY (checkpoint_template_id) REFERENCES checkpoint_templates(checkpoint_template_id),
  UNIQUE(transport_job_id, sequence)
);

CREATE TABLE IF NOT EXISTS location_events (
  location_event_id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  transport_job_id TEXT NOT NULL,
  vehicle_snapshot_id TEXT,
  source_type TEXT NOT NULL,
  provider_code TEXT,
  source_event_id TEXT,
  latitude REAL,
  longitude REAL,
  accuracy_m REAL,
  speed_kph REAL,
  heading REAL,
  place_name TEXT,
  occurred_at TEXT NOT NULL,
  received_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  quality_status TEXT NOT NULL DEFAULT 'VALID',
  raw_payload_ref TEXT,
  actor_id TEXT,
  device_id TEXT,
  idempotency_key TEXT NOT NULL,
  signature_valid INTEGER NOT NULL DEFAULT 1,
  mapping_status TEXT NOT NULL DEFAULT 'MAPPED',
  FOREIGN KEY (transport_job_id) REFERENCES transport_jobs(transport_job_id),
  FOREIGN KEY (vehicle_snapshot_id) REFERENCES vehicle_driver_snapshots(vehicle_driver_snapshot_id),
  UNIQUE(tenant_id, idempotency_key),
  UNIQUE(provider_code, source_event_id)
);

CREATE INDEX IF NOT EXISTS idx_location_events_job_time
  ON location_events(transport_job_id, occurred_at DESC);

CREATE TABLE IF NOT EXISTS custody_transfers (
  custody_transfer_id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  shipment_id TEXT NOT NULL,
  transport_job_id TEXT,
  transfer_type TEXT NOT NULL,
  handover_from_party TEXT NOT NULL,
  handover_to_party TEXT NOT NULL,
  pieces INTEGER NOT NULL,
  weight_kg REAL,
  seal_number TEXT,
  reconciliation_status TEXT NOT NULL DEFAULT 'PENDING',
  submitted_by TEXT NOT NULL,
  accepted_by TEXT,
  submitted_at TEXT NOT NULL,
  accepted_at TEXT,
  evidence_refs_json TEXT NOT NULL DEFAULT '[]',
  status TEXT NOT NULL DEFAULT 'PENDING',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELLED')),
  FOREIGN KEY (shipment_id) REFERENCES shipments(shipment_id),
  FOREIGN KEY (transport_job_id) REFERENCES transport_jobs(transport_job_id)
);

CREATE TABLE IF NOT EXISTS port_service_calendars (
  calendar_id TEXT PRIMARY KEY,
  port_pair_code TEXT NOT NULL,
  version_no INTEGER NOT NULL,
  valid_from TEXT NOT NULL,
  valid_to TEXT NOT NULL,
  timezone_cn TEXT NOT NULL,
  timezone_kz TEXT NOT NULL,
  open_days_json TEXT NOT NULL DEFAULT '[]',
  daily_windows_json TEXT NOT NULL DEFAULT '[]',
  closure_periods_json TEXT NOT NULL DEFAULT '[]',
  appointment_required INTEGER NOT NULL DEFAULT 1,
  restrictions_json TEXT NOT NULL DEFAULT '{}',
  capacity_note TEXT,
  source_type TEXT NOT NULL,
  source_ref TEXT,
  confirmed_by TEXT,
  confirmed_at TEXT,
  next_verify_at TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'UNKNOWN',
  approved_by TEXT,
  published_at TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (status IN ('CONFIRMED', 'STALE', 'CLOSED', 'TEMPORARILY_RESTRICTED', 'UNKNOWN')),
  UNIQUE(port_pair_code, version_no)
);

CREATE TABLE IF NOT EXISTS border_operations (
  border_operation_id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  transport_job_id TEXT NOT NULL,
  operation_control_plan_id TEXT,
  port_pair_code TEXT NOT NULL DEFAULT 'ALASHANKOU_DOSTYK',
  cn_port_code TEXT NOT NULL DEFAULT 'ALASHANKOU',
  kz_port_code TEXT NOT NULL DEFAULT 'DOSTYK',
  operation_mode TEXT,
  operation_mode_verification_status TEXT NOT NULL DEFAULT 'UNCONFIRMED',
  mode_evidence_ref TEXT,
  status TEXT NOT NULL DEFAULT 'PLANNED',
  health_color TEXT NOT NULL DEFAULT 'UNKNOWN',
  incident_owner_id TEXT,
  planned_cn_arrival_at TEXT,
  forecast_cn_arrival_at TEXT,
  actual_cn_arrival_at TEXT,
  planned_cn_exit_at TEXT,
  planned_kz_transfer_complete_at TEXT,
  forecast_total_port_duration_minutes INTEGER,
  cn_queue_no TEXT,
  cn_queue_ahead_count INTEGER,
  cn_open_window_count INTEGER,
  cn_next_update_at TEXT,
  cn_gate_in_at TEXT,
  cn_release_at TEXT,
  cn_exit_at TEXT,
  dostyk_arrival_at TEXT,
  kz_inspection_status TEXT,
  kz_release_at TEXT,
  dostyk_departure_at TEXT,
  cn_vehicle_snapshot_id TEXT,
  kz_vehicle_snapshot_id TEXT,
  active_vehicle_mapping_id TEXT,
  seal_before TEXT,
  seal_after TEXT,
  seal_continuity_status TEXT,
  pieces_before INTEGER,
  pieces_after INTEGER,
  weight_before_kg REAL,
  weight_after_kg REAL,
  reconciliation_status TEXT NOT NULL DEFAULT 'PENDING',
  cmr_document_id TEXT,
  declaration_refs_json TEXT NOT NULL DEFAULT '[]',
  release_evidence_refs_json TEXT NOT NULL DEFAULT '[]',
  handover_id TEXT,
  port_service_calendar_id TEXT,
  last_external_status_at TEXT,
  china_exit_gate_decision_id TEXT,
  dostyk_departure_gate_decision_id TEXT,
  row_version INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at TEXT,
  CHECK (status IN ('PLANNED', 'PRE_ALERTED', 'APPROACHING_ALASHANKOU', 'QUEUED_CN', 'GATE_IN_CN', 'CN_OPERATION_IN_PROGRESS', 'CN_RELEASED', 'EXITED_CN', 'ARRIVED_DOSTYK', 'KZ_ENTRY_IN_PROGRESS', 'KZ_RELEASED', 'KZ_HANDOVER_IN_PROGRESS', 'DEPARTED_DOSTYK', 'BLOCKED', 'CANCELLED')),
  FOREIGN KEY (transport_job_id) REFERENCES transport_jobs(transport_job_id),
  FOREIGN KEY (port_service_calendar_id) REFERENCES port_service_calendars(calendar_id)
);

CREATE INDEX IF NOT EXISTS idx_border_operations_status
  ON border_operations(status, health_color, updated_at);

CREATE TABLE IF NOT EXISTS cross_border_vehicle_mappings (
  mapping_id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  border_operation_id TEXT NOT NULL,
  mapping_version INTEGER NOT NULL,
  cn_vehicle_snapshot_id TEXT NOT NULL,
  kz_vehicle_snapshot_id TEXT NOT NULL,
  mapping_type TEXT NOT NULL,
  effective_at TEXT NOT NULL,
  handover_party_from TEXT NOT NULL,
  handover_party_to TEXT NOT NULL,
  custody_transfer_id TEXT,
  pieces_match_result TEXT NOT NULL,
  weight_match_result TEXT NOT NULL,
  seal_match_result TEXT NOT NULL,
  change_reason TEXT,
  evidence_refs_json TEXT NOT NULL DEFAULT '[]',
  submitted_by TEXT NOT NULL,
  approved_by TEXT NOT NULL,
  active_flag INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (mapping_type IN ('SAME_VEHICLE', 'TRACTOR_SWAP', 'TRAILER_HANDOVER', 'FULL_VEHICLE_SWAP', 'CARGO_TRANSLOAD', 'MIXED')),
  CHECK (submitted_by <> approved_by),
  FOREIGN KEY (border_operation_id) REFERENCES border_operations(border_operation_id),
  FOREIGN KEY (cn_vehicle_snapshot_id) REFERENCES vehicle_driver_snapshots(vehicle_driver_snapshot_id),
  FOREIGN KEY (kz_vehicle_snapshot_id) REFERENCES vehicle_driver_snapshots(vehicle_driver_snapshot_id),
  FOREIGN KEY (custody_transfer_id) REFERENCES custody_transfers(custody_transfer_id),
  UNIQUE(border_operation_id, mapping_version)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_cross_border_mapping_active
  ON cross_border_vehicle_mappings(border_operation_id)
  WHERE active_flag = 1;

CREATE TABLE IF NOT EXISTS airport_receipt_sessions (
  airport_receipt_session_id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  transport_job_id TEXT NOT NULL,
  shipment_id TEXT NOT NULL,
  airport_code TEXT NOT NULL DEFAULT 'TAS',
  flight_id TEXT,
  awb_ids_json TEXT NOT NULL DEFAULT '[]',
  status TEXT NOT NULL DEFAULT 'WAITING_TRUCK',
  truck_arrived_at TEXT,
  seal_checked_at TEXT,
  unloading_started_at TEXT,
  unloading_completed_at TEXT,
  count_completed_at TEXT,
  warehouse_out_pieces INTEGER NOT NULL DEFAULT 0,
  truck_loaded_pieces INTEGER NOT NULL DEFAULT 0,
  airport_received_pieces INTEGER NOT NULL DEFAULT 0,
  matched_pieces INTEGER NOT NULL DEFAULT 0,
  missing_pieces INTEGER NOT NULL DEFAULT 0,
  unexpected_pieces INTEGER NOT NULL DEFAULT 0,
  damaged_pieces INTEGER NOT NULL DEFAULT 0,
  seal_expected TEXT,
  seal_actual TEXT,
  seal_condition TEXT,
  handover_from TEXT,
  received_by TEXT,
  handover_at TEXT,
  reconciliation_result_id TEXT,
  gate_decision_id TEXT,
  evidence_refs_json TEXT NOT NULL DEFAULT '[]',
  row_version INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (status IN ('WAITING_TRUCK', 'ARRIVED_STAGING', 'TRUCK_ARRIVED', 'SEAL_CHECK_PENDING', 'UNLOADING', 'COUNTING', 'RECONCILIATION_PENDING', 'MATCHED', 'DISCREPANCY_REVIEW', 'ACCEPTED', 'CONDITIONAL_ACCEPTED', 'REJECTED_OR_QUARANTINED', 'COMPLETED')),
  FOREIGN KEY (transport_job_id) REFERENCES transport_jobs(transport_job_id),
  FOREIGN KEY (shipment_id) REFERENCES shipments(shipment_id),
  FOREIGN KEY (flight_id) REFERENCES flights(flight_id),
  FOREIGN KEY (gate_decision_id) REFERENCES gate_decisions(gate_decision_id)
);

CREATE TABLE IF NOT EXISTS reconciliation_results (
  reconciliation_result_id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  airport_receipt_session_id TEXT NOT NULL,
  shipment_id TEXT NOT NULL,
  warehouse_out_pieces INTEGER NOT NULL,
  truck_loaded_pieces INTEGER NOT NULL,
  airport_received_pieces INTEGER NOT NULL,
  matched_pieces INTEGER NOT NULL DEFAULT 0,
  missing_pieces INTEGER NOT NULL DEFAULT 0,
  unexpected_pieces INTEGER NOT NULL DEFAULT 0,
  duplicate_pieces INTEGER NOT NULL DEFAULT 0,
  wrong_shipment_pieces INTEGER NOT NULL DEFAULT 0,
  aggregate_review_pieces INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL,
  differences_json TEXT NOT NULL DEFAULT '[]',
  input_event_refs_json TEXT NOT NULL DEFAULT '[]',
  calculated_at TEXT NOT NULL,
  rule_version TEXT NOT NULL,
  FOREIGN KEY (airport_receipt_session_id) REFERENCES airport_receipt_sessions(airport_receipt_session_id),
  FOREIGN KEY (shipment_id) REFERENCES shipments(shipment_id)
);

CREATE INDEX IF NOT EXISTS idx_airport_receipts_transport
  ON airport_receipt_sessions(transport_job_id, status);
