CREATE TABLE IF NOT EXISTS business_handover_events (
  business_handover_event_id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  flight_id TEXT NOT NULL,
  event_type TEXT NOT NULL,
  occurred_at TEXT NOT NULL,
  source_party_id TEXT,
  status TEXT NOT NULL DEFAULT 'RECEIVED',
  payload_json TEXT NOT NULL,
  evidence_refs_json TEXT NOT NULL DEFAULT '[]',
  submitted_by TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (flight_id) REFERENCES flights(flight_id)
);

CREATE TABLE IF NOT EXISTS cargo_pool_versions (
  cargo_pool_version_id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  flight_id TEXT NOT NULL,
  version_no INTEGER NOT NULL,
  status TEXT NOT NULL DEFAULT 'DRAFT',
  total_shipments INTEGER NOT NULL DEFAULT 0,
  total_pieces INTEGER NOT NULL DEFAULT 0,
  total_weight_kg REAL NOT NULL DEFAULT 0,
  shipment_refs_json TEXT NOT NULL DEFAULT '[]',
  source_event_refs_json TEXT NOT NULL DEFAULT '[]',
  change_reason TEXT,
  requested_by TEXT NOT NULL,
  approved_by TEXT,
  published_at TEXT,
  supersedes_version_id TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (status IN ('DRAFT', 'IN_REVIEW', 'PUBLISHED', 'SUPERSEDED')),
  FOREIGN KEY (flight_id) REFERENCES flights(flight_id),
  FOREIGN KEY (supersedes_version_id) REFERENCES cargo_pool_versions(cargo_pool_version_id),
  UNIQUE(flight_id, version_no)
);

CREATE TABLE IF NOT EXISTS operation_control_plans (
  operation_control_plan_id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  project_code TEXT NOT NULL,
  flight_id TEXT NOT NULL,
  route_template_id TEXT NOT NULL,
  baseline_etd TEXT NOT NULL,
  current_operating_etd TEXT NOT NULL,
  flight_timezone TEXT NOT NULL,
  origin_start_event_type TEXT NOT NULL DEFAULT 'SZX_TRUCK_DEPARTED',
  origin_start_at TEXT,
  pre_carriage_kpi_code TEXT NOT NULL DEFAULT 'PRE_CARRIAGE_TO_TAS_DEP',
  pre_carriage_target_minutes INTEGER NOT NULL DEFAULT 12960,
  pre_carriage_hard_limit_minutes INTEGER NOT NULL DEFAULT 14400,
  a_b_control_end_event_type TEXT NOT NULL DEFAULT 'LGG_ATA_CONFIRMED',
  a_b_handover_end_event_type TEXT NOT NULL DEFAULT 'B2_OBI_HANDOVER_ACCEPTED',
  external_execution_party_id TEXT NOT NULL DEFAULT 'SMDG',
  c_d_interface_role TEXT NOT NULL DEFAULT 'OBI_OVERSEAS_INTERFACE',
  internal_product_target_minutes INTEGER,
  customer_commitment_minutes INTEGER,
  product_end_event_type TEXT,
  flight_duty_plan_id TEXT,
  active_occ_dm_assignment_id TEXT,
  active_control_segment TEXT NOT NULL DEFAULT 'A1',
  single_source_record_version INTEGER NOT NULL DEFAULT 1,
  evidence_package_status TEXT NOT NULL DEFAULT 'INCOMPLETE',
  active_plan_version_id TEXT,
  status TEXT NOT NULL DEFAULT 'DRAFT',
  overall_health_color TEXT NOT NULL DEFAULT 'UNKNOWN',
  next_hard_milestone_id TEXT,
  remaining_buffer_minutes INTEGER,
  last_calculated_at TEXT,
  calculation_status TEXT NOT NULL DEFAULT 'PENDING',
  current_coverage_status TEXT NOT NULL DEFAULT 'GAP',
  row_version INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (status IN ('DRAFT', 'IN_REVIEW', 'ACTIVE', 'PAUSED', 'CLOSED', 'CANCELLED')),
  CHECK (overall_health_color IN ('UNKNOWN', 'BLUE', 'YELLOW', 'RED')),
  CHECK (current_coverage_status IN ('COVERED', 'AT_RISK', 'GAP')),
  FOREIGN KEY (flight_id) REFERENCES flights(flight_id),
  FOREIGN KEY (route_template_id) REFERENCES route_templates(route_template_id),
  UNIQUE(tenant_id, flight_id)
);

CREATE TABLE IF NOT EXISTS operation_control_plan_versions (
  plan_version_id TEXT PRIMARY KEY,
  operation_control_plan_id TEXT NOT NULL,
  version_no INTEGER NOT NULL,
  baseline_etd_snapshot TEXT NOT NULL,
  operating_etd_snapshot TEXT NOT NULL,
  route_template_version INTEGER NOT NULL,
  kpi_rule_set_version TEXT NOT NULL,
  responsibility_rule_version TEXT NOT NULL,
  flight_duty_plan_version INTEGER,
  source_status TEXT NOT NULL,
  source_approval_status TEXT NOT NULL,
  change_reason TEXT NOT NULL,
  source_ref TEXT,
  requested_by TEXT NOT NULL,
  approved_by TEXT,
  published_at TEXT,
  supersedes_version_id TEXT,
  active_from TEXT,
  active_to TEXT,
  frozen_baseline_flag INTEGER NOT NULL DEFAULT 0,
  active_flag INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (operation_control_plan_id) REFERENCES operation_control_plans(operation_control_plan_id),
  FOREIGN KEY (supersedes_version_id) REFERENCES operation_control_plan_versions(plan_version_id),
  UNIQUE(operation_control_plan_id, version_no)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_operation_plan_active_version
  ON operation_control_plan_versions(operation_control_plan_id)
  WHERE active_flag = 1;

CREATE TABLE IF NOT EXISTS role_qualifications (
  role_qualification_id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  role_code TEXT NOT NULL,
  authorization_level TEXT NOT NULL,
  station_scope_ids_json TEXT NOT NULL DEFAULT '[]',
  region_scope_codes_json TEXT NOT NULL DEFAULT '[]',
  business_scope_codes_json TEXT NOT NULL DEFAULT '[]',
  status TEXT NOT NULL DEFAULT 'PENDING',
  valid_from TEXT NOT NULL,
  valid_to TEXT,
  training_record_refs_json TEXT NOT NULL DEFAULT '[]',
  assessment_result_ref TEXT,
  approved_by TEXT,
  approved_at TEXT,
  revoked_by TEXT,
  revoked_reason TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (authorization_level IN ('L1_INPUT', 'L2_CONTROL', 'L3_DECISION')),
  CHECK (status IN ('PENDING', 'ACTIVE', 'SUSPENDED', 'EXPIRED', 'REVOKED')),
  FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE INDEX IF NOT EXISTS idx_role_qualifications_user_role
  ON role_qualifications(user_id, role_code, status, valid_from, valid_to);

CREATE TABLE IF NOT EXISTS contact_directory_entries (
  contact_entry_id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  party_id TEXT NOT NULL,
  location_code TEXT NOT NULL,
  service_scope TEXT NOT NULL,
  primary_contact_ref TEXT NOT NULL,
  backup_contact_ref TEXT NOT NULL,
  organization_channel_ref TEXT NOT NULL,
  phone_encrypted TEXT,
  instant_message_encrypted TEXT,
  email_encrypted TEXT,
  available_hours_json TEXT NOT NULL DEFAULT '{}',
  timezone TEXT NOT NULL,
  supports_24h INTEGER NOT NULL DEFAULT 0,
  verified_at TEXT,
  verified_by TEXT,
  next_verify_at TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'UNVERIFIED',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (status IN ('UNVERIFIED', 'VERIFIED', 'STALE', 'DISABLED'))
);

CREATE TABLE IF NOT EXISTS flight_duty_plans (
  flight_duty_plan_id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  flight_id TEXT NOT NULL,
  operation_control_plan_id TEXT NOT NULL,
  version_no INTEGER NOT NULL,
  status TEXT NOT NULL DEFAULT 'DRAFT',
  required_role_codes_json TEXT NOT NULL,
  missing_role_codes_json TEXT NOT NULL DEFAULT '[]',
  contact_readiness_status TEXT NOT NULL DEFAULT 'INCOMPLETE',
  coverage_mode TEXT NOT NULL DEFAULT 'HYBRID_FUNCTION_DUTY',
  shift_scheme_code TEXT NOT NULL,
  minimum_active_seats INTEGER NOT NULL DEFAULT 2,
  current_segment_code TEXT NOT NULL DEFAULT 'A1',
  current_coverage_status TEXT NOT NULL DEFAULT 'GAP',
  active_occ_dm_assignment_id TEXT,
  active_segment_owner_assignment_id TEXT,
  coverage_last_checked_at TEXT,
  valid_from TEXT NOT NULL,
  valid_to TEXT,
  approved_by TEXT,
  activated_at TEXT,
  closed_at TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (status IN ('DRAFT', 'READINESS_PENDING', 'READY', 'ACTIVE', 'CLOSED')),
  CHECK (current_coverage_status IN ('COVERED', 'AT_RISK', 'GAP')),
  FOREIGN KEY (flight_id) REFERENCES flights(flight_id),
  FOREIGN KEY (operation_control_plan_id) REFERENCES operation_control_plans(operation_control_plan_id),
  UNIQUE(flight_id, version_no)
);

CREATE TABLE IF NOT EXISTS control_role_assignments (
  assignment_id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  flight_duty_plan_id TEXT NOT NULL,
  role_code TEXT NOT NULL,
  role_qualification_id TEXT NOT NULL,
  assignment_type TEXT NOT NULL,
  primary_user_id TEXT NOT NULL,
  backup_user_id TEXT,
  contact_directory_entry_id TEXT NOT NULL,
  segment_scope_codes_json TEXT NOT NULL DEFAULT '[]',
  object_scope_refs_json TEXT NOT NULL DEFAULT '[]',
  authorization_level_snapshot TEXT NOT NULL,
  shift_start_at TEXT NOT NULL,
  shift_end_at TEXT NOT NULL,
  timezone TEXT NOT NULL,
  duty_status TEXT NOT NULL DEFAULT 'SCHEDULED',
  activated_at TEXT,
  activated_by TEXT,
  activation_reason TEXT,
  temporary_permission_expires_at TEXT,
  stood_down_at TEXT,
  stood_down_by TEXT,
  accepted_at TEXT,
  acceptance_status TEXT NOT NULL DEFAULT 'PENDING',
  replaced_assignment_id TEXT,
  effective_from TEXT NOT NULL,
  effective_to TEXT,
  assigned_by TEXT NOT NULL,
  approved_by TEXT NOT NULL,
  incident_id TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (assignment_type IN ('PRIMARY_DUTY', 'BACKUP_ON_CALL', 'TEMP_AUGMENT')),
  CHECK (duty_status IN ('SCHEDULED', 'ON_CALL', 'ON_DUTY', 'TEMP_ACTIVATED', 'HANDOVER_PENDING', 'ENDED', 'CANCELLED')),
  CHECK (assigned_by <> approved_by),
  FOREIGN KEY (flight_duty_plan_id) REFERENCES flight_duty_plans(flight_duty_plan_id),
  FOREIGN KEY (role_qualification_id) REFERENCES role_qualifications(role_qualification_id),
  FOREIGN KEY (primary_user_id) REFERENCES users(user_id),
  FOREIGN KEY (contact_directory_entry_id) REFERENCES contact_directory_entries(contact_entry_id),
  FOREIGN KEY (replaced_assignment_id) REFERENCES control_role_assignments(assignment_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_active_primary_assignment
  ON control_role_assignments(flight_duty_plan_id, role_code, shift_start_at, shift_end_at)
  WHERE assignment_type = 'PRIMARY_DUTY' AND duty_status IN ('SCHEDULED', 'ON_DUTY', 'HANDOVER_PENDING');

CREATE TABLE IF NOT EXISTS control_handovers (
  handover_id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  operation_control_plan_id TEXT NOT NULL,
  handover_type TEXT NOT NULL DEFAULT 'CONTROL_SEGMENT',
  gate_code TEXT NOT NULL,
  from_segment TEXT NOT NULL,
  from_assignment_id TEXT NOT NULL,
  to_segment TEXT NOT NULL,
  to_assignment_id TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'PENDING',
  current_location TEXT,
  last_evidence_refs_json TEXT NOT NULL DEFAULT '[]',
  latest_eta_at TEXT,
  next_gate_code TEXT,
  remaining_buffer_minutes INTEGER,
  open_hold_ids_json TEXT NOT NULL DEFAULT '[]',
  incident_owner_id TEXT,
  next_update_at TEXT,
  submitted_at TEXT NOT NULL,
  accepted_at TEXT,
  rejection_reason TEXT,
  previous_owner_released_at TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (handover_type IN ('CONTROL_SEGMENT', 'SHIFT')),
  CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED', 'EXPIRED', 'CANCELLED')),
  FOREIGN KEY (operation_control_plan_id) REFERENCES operation_control_plans(operation_control_plan_id),
  FOREIGN KEY (from_assignment_id) REFERENCES control_role_assignments(assignment_id),
  FOREIGN KEY (to_assignment_id) REFERENCES control_role_assignments(assignment_id)
);

CREATE TABLE IF NOT EXISTS resource_readiness_checks (
  readiness_check_id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  operation_control_plan_id TEXT NOT NULL,
  resource_scope TEXT NOT NULL,
  check_item_code TEXT NOT NULL,
  required_value TEXT,
  actual_value TEXT,
  blocking_level TEXT NOT NULL DEFAULT 'WARNING',
  status TEXT NOT NULL DEFAULT 'UNKNOWN',
  primary_supplier_id TEXT,
  backup_supplier_id TEXT,
  replacement_eta_minutes INTEGER,
  evidence_refs_json TEXT NOT NULL DEFAULT '[]',
  checked_by TEXT,
  checked_at TEXT,
  valid_until TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (resource_scope IN ('PREWAREHOUSE', 'DOMESTIC_TRUCKING', 'BORDER_OPERATION', 'KZ_TRANSPORT', 'YALLAMA', 'TAS_STATION', 'FLIGHT_INFORMATION', 'SMDG_CD')),
  CHECK (status IN ('UNKNOWN', 'READY', 'PARTIAL', 'NOT_READY', 'EXPIRED')),
  FOREIGN KEY (operation_control_plan_id) REFERENCES operation_control_plans(operation_control_plan_id),
  UNIQUE(operation_control_plan_id, resource_scope, check_item_code)
);

CREATE TABLE IF NOT EXISTS decision_records (
  decision_record_id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  operation_control_plan_id TEXT NOT NULL,
  source_channel TEXT NOT NULL,
  occurred_at TEXT NOT NULL,
  must_record_by TEXT NOT NULL,
  recorded_at TEXT NOT NULL,
  late_record_reason TEXT,
  decision_type TEXT NOT NULL,
  decision_text TEXT NOT NULL,
  affected_object_refs_json TEXT NOT NULL DEFAULT '[]',
  affected_gate_codes_json TEXT NOT NULL DEFAULT '[]',
  requested_by TEXT NOT NULL,
  approved_by TEXT NOT NULL,
  evidence_refs_json TEXT NOT NULL DEFAULT '[]',
  status TEXT NOT NULL DEFAULT 'APPROVED',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (source_channel IN ('SYSTEM', 'PHONE', 'GROUP_CHAT', 'EMAIL', 'MEETING')),
  CHECK (decision_type IN ('PORT_CHANGE', 'PRIORITY_CHANGE', 'OFFLOAD', 'PAYLOAD_REDUCTION', 'ETA_OVERRIDE', 'RECOVERY_PLAN', 'OTHER')),
  CHECK (requested_by <> approved_by),
  FOREIGN KEY (operation_control_plan_id) REFERENCES operation_control_plans(operation_control_plan_id)
);

CREATE TABLE IF NOT EXISTS external_execution_statuses (
  external_status_id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  operation_control_plan_id TEXT NOT NULL,
  execution_party_id TEXT NOT NULL DEFAULT 'SMDG',
  stage_code TEXT NOT NULL,
  planned_at TEXT,
  forecast_at TEXT,
  actual_at TEXT,
  external_sla_rule_id TEXT,
  status TEXT NOT NULL,
  blocker_code TEXT,
  next_update_at TEXT,
  evidence_refs_json TEXT NOT NULL DEFAULT '[]',
  obi_owner_assignment_id TEXT NOT NULL,
  source_contact_entry_id TEXT NOT NULL,
  source_statement_ref TEXT NOT NULL,
  recorded_at TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (stage_code IN ('LGG_RECEIPT', 'PICKUP', 'BREAKDOWN', 'CUSTOMS_REVIEW', 'CUSTOMS_RELEASE', 'DELIVERY', 'POD', 'BUSINESS_CLOSE')),
  FOREIGN KEY (operation_control_plan_id) REFERENCES operation_control_plans(operation_control_plan_id),
  FOREIGN KEY (obi_owner_assignment_id) REFERENCES control_role_assignments(assignment_id),
  FOREIGN KEY (source_contact_entry_id) REFERENCES contact_directory_entries(contact_entry_id)
);

CREATE TABLE IF NOT EXISTS milestone_definitions (
  milestone_definition_id TEXT PRIMARY KEY,
  route_template_id TEXT NOT NULL,
  template_version INTEGER NOT NULL,
  milestone_code TEXT NOT NULL,
  name_zh TEXT NOT NULL,
  name_en TEXT NOT NULL,
  sequence INTEGER NOT NULL,
  stage_code TEXT NOT NULL,
  anchor_event_type TEXT NOT NULL DEFAULT 'FLIGHT_ETD',
  offset_minutes INTEGER NOT NULL,
  deadline_type TEXT NOT NULL,
  start_milestone_code TEXT,
  target_duration_minutes INTEGER,
  warning_thresholds_json TEXT NOT NULL DEFAULT '{}',
  yellow_rule_expression TEXT,
  red_rule_expression TEXT,
  required_fields_json TEXT NOT NULL DEFAULT '[]',
  required_evidence_types_json TEXT NOT NULL DEFAULT '[]',
  closure_expression TEXT NOT NULL,
  owner_role TEXT NOT NULL,
  execution_party_role TEXT,
  next_owner_role TEXT,
  responsibility_scope TEXT NOT NULL,
  source_document_ref TEXT NOT NULL,
  source_section_ref TEXT NOT NULL,
  validation_status TEXT NOT NULL,
  gate_code TEXT,
  freeze_next_gate_on_red INTEGER NOT NULL DEFAULT 0,
  active_from TEXT,
  active_to TEXT,
  CHECK (deadline_type IN ('TARGET', 'WARNING', 'HARD_DEADLINE', 'CUSTOMER_COMMITMENT', 'EXTERNAL_SLA', 'OBSERVATION')),
  CHECK (validation_status IN ('ACTIVE', 'TO_BE_CONFIRMED', 'LEGACY_SUMMARY', 'RETIRED')),
  FOREIGN KEY (route_template_id) REFERENCES route_templates(route_template_id),
  UNIQUE(route_template_id, template_version, milestone_code),
  UNIQUE(route_template_id, template_version, sequence)
);

CREATE TABLE IF NOT EXISTS milestone_instances (
  milestone_instance_id TEXT PRIMARY KEY,
  operation_control_plan_id TEXT NOT NULL,
  plan_version_id TEXT NOT NULL,
  milestone_definition_id TEXT NOT NULL,
  related_transport_job_id TEXT,
  related_vehicle_id TEXT,
  related_uld_id TEXT,
  baseline_planned_at TEXT NOT NULL,
  operating_planned_at TEXT NOT NULL,
  forecast_at TEXT,
  forecast_source TEXT,
  forecast_confidence REAL,
  actual_started_at TEXT,
  actual_completed_at TEXT,
  baseline_variance_minutes INTEGER,
  operating_variance_minutes INTEGER,
  remaining_buffer_minutes INTEGER,
  health_color TEXT NOT NULL DEFAULT 'UNKNOWN',
  status TEXT NOT NULL DEFAULT 'PENDING',
  evidence_state TEXT NOT NULL DEFAULT 'MISSING',
  closure_evidence_ids_json TEXT NOT NULL DEFAULT '[]',
  closed_by TEXT,
  closed_at TEXT,
  incident_id TEXT,
  last_status_reason TEXT,
  last_calculated_at TEXT,
  row_version INTEGER NOT NULL DEFAULT 1,
  CHECK (health_color IN ('UNKNOWN', 'BLUE', 'YELLOW', 'RED')),
  CHECK (status IN ('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CLOSED', 'MISSED', 'WAIVED', 'BLOCKED')),
  FOREIGN KEY (operation_control_plan_id) REFERENCES operation_control_plans(operation_control_plan_id),
  FOREIGN KEY (plan_version_id) REFERENCES operation_control_plan_versions(plan_version_id),
  FOREIGN KEY (milestone_definition_id) REFERENCES milestone_definitions(milestone_definition_id),
  FOREIGN KEY (related_transport_job_id) REFERENCES transport_jobs(transport_job_id)
);

CREATE TABLE IF NOT EXISTS kpi_status_snapshots (
  kpi_snapshot_id TEXT PRIMARY KEY,
  operation_control_plan_id TEXT NOT NULL,
  plan_version_id TEXT NOT NULL,
  scope_type TEXT NOT NULL,
  scope_id TEXT NOT NULL,
  snapshot_at TEXT NOT NULL,
  current_stage TEXT,
  overall_health_color TEXT NOT NULL,
  next_milestone_id TEXT,
  next_hard_deadline_at TEXT,
  forecast_at TEXT,
  variance_minutes INTEGER,
  remaining_buffer_minutes INTEGER,
  last_valid_location_at TEXT,
  location_age_minutes INTEGER,
  open_incident_count INTEGER NOT NULL DEFAULT 0,
  highest_severity TEXT,
  rule_results_json TEXT NOT NULL,
  rule_set_version TEXT NOT NULL,
  input_event_refs_json TEXT NOT NULL DEFAULT '[]',
  deterministic_hash TEXT NOT NULL,
  FOREIGN KEY (operation_control_plan_id) REFERENCES operation_control_plans(operation_control_plan_id),
  FOREIGN KEY (plan_version_id) REFERENCES operation_control_plan_versions(plan_version_id)
);

CREATE INDEX IF NOT EXISTS idx_kpi_snapshots_plan_time
  ON kpi_status_snapshots(operation_control_plan_id, snapshot_at DESC);

CREATE TABLE IF NOT EXISTS change_requests (
  change_request_id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  operation_control_plan_id TEXT,
  related_object_type TEXT NOT NULL,
  related_object_id TEXT NOT NULL,
  change_type TEXT NOT NULL,
  before_json TEXT NOT NULL,
  after_json TEXT NOT NULL,
  reason TEXT NOT NULL,
  requested_by TEXT NOT NULL,
  approved_by TEXT,
  status TEXT NOT NULL DEFAULT 'PENDING',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  approved_at TEXT,
  CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'APPLIED', 'CANCELLED')),
  CHECK (approved_by IS NULL OR requested_by <> approved_by),
  FOREIGN KEY (operation_control_plan_id) REFERENCES operation_control_plans(operation_control_plan_id)
);

CREATE TABLE IF NOT EXISTS flight_cargo_master_records (
  flight_cargo_master_record_id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  flight_id TEXT NOT NULL,
  operation_control_plan_id TEXT NOT NULL,
  record_version INTEGER NOT NULL,
  record_status TEXT NOT NULL,
  planned_pieces INTEGER NOT NULL DEFAULT 0,
  planned_weight_kg REAL NOT NULL DEFAULT 0,
  tas_received_pieces INTEGER NOT NULL DEFAULT 0,
  tas_received_weight_kg REAL NOT NULL DEFAULT 0,
  security_entered_pieces INTEGER NOT NULL DEFAULT 0,
  security_passed_pieces INTEGER NOT NULL DEFAULT 0,
  security_held_pieces INTEGER NOT NULL DEFAULT 0,
  security_returned_pieces INTEGER NOT NULL DEFAULT 0,
  buildup_pieces INTEGER NOT NULL DEFAULT 0,
  handed_to_airline_pieces INTEGER NOT NULL DEFAULT 0,
  loaded_pieces INTEGER NOT NULL DEFAULT 0,
  uld_ids_json TEXT NOT NULL DEFAULT '[]',
  cba_version_id TEXT,
  manifest_document_id TEXT,
  exception_ids_json TEXT NOT NULL DEFAULT '[]',
  change_request_ids_json TEXT NOT NULL DEFAULT '[]',
  maintained_by TEXT NOT NULL,
  reviewed_by TEXT,
  frozen_by TEXT,
  frozen_at TEXT,
  source_event_refs_json TEXT NOT NULL DEFAULT '[]',
  record_hash TEXT NOT NULL,
  active_flag INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (record_status IN ('WORKING', 'INITIAL_FROZEN', 'FINAL_CBA_FROZEN', 'MANIFEST_FROZEN', 'SUPERSEDED')),
  FOREIGN KEY (flight_id) REFERENCES flights(flight_id),
  FOREIGN KEY (operation_control_plan_id) REFERENCES operation_control_plans(operation_control_plan_id),
  UNIQUE(flight_id, record_version)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_flight_cargo_master_active
  ON flight_cargo_master_records(flight_id)
  WHERE active_flag = 1;

CREATE TABLE IF NOT EXISTS incident_updates (
  incident_update_id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  exception_id TEXT NOT NULL,
  update_type TEXT NOT NULL,
  health_color TEXT NOT NULL,
  occurred_at TEXT NOT NULL,
  location_text TEXT,
  confirmed_facts TEXT NOT NULL,
  cargo_vehicle_position TEXT,
  current_hold TEXT,
  affected_next_milestone_id TEXT,
  latest_eta TEXT,
  remaining_buffer_minutes INTEGER,
  incident_owner_id TEXT,
  actions_taken TEXT,
  coordination_needed TEXT,
  next_update_at TEXT,
  customer_message_status TEXT,
  evidence_ids_json TEXT NOT NULL DEFAULT '[]',
  created_by TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (update_type IN ('ACK', 'FIRST_REPORT', 'PERIODIC_UPDATE', 'RECOVERY', 'CLOSURE', 'CAPA')),
  CHECK (health_color IN ('BLUE', 'YELLOW', 'RED')),
  FOREIGN KEY (exception_id) REFERENCES exceptions(exception_id)
);

CREATE TABLE IF NOT EXISTS resource_capacity_plans (
  resource_capacity_plan_id TEXT PRIMARY KEY,
  operation_control_plan_id TEXT NOT NULL,
  plan_version_id TEXT NOT NULL,
  hourly_plan_json TEXT NOT NULL,
  resources_json TEXT NOT NULL,
  capacity_per_hour REAL NOT NULL,
  forecast_workload_per_hour REAL NOT NULL,
  utilization_percent REAL NOT NULL,
  shortage_start_at TEXT,
  shortage_resource_type TEXT,
  backup_plan_ref TEXT,
  resource_health_color TEXT NOT NULL DEFAULT 'UNKNOWN',
  approved_by TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (operation_control_plan_id) REFERENCES operation_control_plans(operation_control_plan_id),
  FOREIGN KEY (plan_version_id) REFERENCES operation_control_plan_versions(plan_version_id)
);
